# Initial state of the FSM

initial_state: "NORMAL_JOYSTICK_CONTROL"

events: # Maps from subscribing topic to signal ids
  joystick_override_on:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: True
  joystick_override_off:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: False
  apriltag_intersection:
    topic: "apriltag_postprocessing_node/apriltags_intersection"
    msg_type: "BoolStamped"
    trigger: True
  at_stop_line:
    topic: "stop_line_filter_node/at_stop_line"
    msg_type: "BoolStamped"
    trigger: True
  intersection_go:
    topic: "coordinator_node/intersection_go"
    msg_type: "BoolStamped"
    trigger: True
  intersection_done: ## closed loop new
    topic: "intersection_navigation_node/intersection_done"
    msg_type: "BoolStamped"
    trigger: True

# Define nodes
nodes:
  decoder_node: "decoder_node/switch"
  anti_instagram: "anti_instagram_node/switch"
  apriltag_node: "apriltag_detector_node/switch"
  led_emitter_node: "led_emitter_node/switch"
  led_detector_node: "led_detector_node/switch"
  line_detector_node: "line_detector_node/switch"
  lane_filter_node: "lane_filter_node/switch"
  stop_line_filter_node: "stop_line_filter_node/switch"
  # extras added

  coordinator_node: "coordinator_node/switch" #NOTE explicit coordination
  unicorn_intersection_node: "unicorn_intersection_node/switch" #NOTE a.k.a. semi closed loop intersection navigation
  lane_controller_node: "lane_controller_node/switch"

# Define state transitions

global_transitions:
  joystick_override_on: "NORMAL_JOYSTICK_CONTROL"

states:
  NORMAL_JOYSTICK_CONTROL:
    transitions:
      joystick_override_off: "LANE_FOLLOWING"
    active_nodes:
      - lane_filter_node
      - line_detector_node
      - stop_line_filter_node
      - ground_projection_node
      - anti_instagram
      - decoder_node
    lights: "GREEN"
    current_status: "implemented"

  LANE_FOLLOWING:
    transitions:
      at_stop_line: "INTERSECTION_COORDINATION"
    active_nodes:
      - anti_instagram
      - decoder_node
      - line_detector_node
      - ground_projection_node
      - lane_filter_node
      - lane_controller_node
      - stop_line_filter_node
    lights: "RED"

  INTERSECTION_COORDINATION:
    transitions:
      intersection_go: "INTERSECTION_CONTROL"
    active_nodes:
      - apriltag_node #NOTE
      - lane_filter_node
      - lane_controller_node
      - line_detector_node # NOTE possibly
      - decoder_node
      - led_emitter_node
      - led_detector_node
      - coordinator_node
      - unicorn_intersection_node
    lights: "WHITE"

  INTERSECTION_CONTROL:
    transitions:
      intersection_done: "LANE_FOLLOWING"
    active_nodes:
      - decoder_node
      - line_detector_node
      - lane_filter_node
      - lane_controller_node
      - unicorn_intersection_node